imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            action_level: debug
            path: "php://stderr"
#            handler: nested
#        nested:
#            type: stream
#            path: "php://stderr"
        console:
            type:  console
            channels: [!event, !doctrine]
