# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        token:
            id: app.provider.user_token
    firewalls:
        public:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            stateless: true
            security: false
        admin:
            guard:
                authenticators:
                    - app.security.authenticator_hour_filter_token
            pattern: ^/admin
            provider: token
            stateless: true
        morozov:
            guard:
                entry_point: app.security.authenticator_public_morozov
                authenticators:
                    - app.security.authenticator_public_morozov
                    - app.security.authenticator_token
            pattern: ^/morozov
            provider: token
            stateless: true
        main:
            guard:
                authenticators:
                    - app.security.authenticator_token
            pattern: ^/
            provider: token
            stateless: true
    access_control:
        - { path: ^/admin, roles: ROLE_MANAGER }
        - { path: ^/, roles: ROLE_CLIENT }
