# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.class.token_authenticator: AppBundle\Security\TokenAuthenticator
    app.class.token_user_provider: AppBundle\Security\User\TokenUserProvider

services:
    app.security.authenticator_token:
        class: "%app.class.token_authenticator%"
    app.security.authenticator_hour_filter_token:
        class: "%app.class.token_authenticator%"
        arguments:
            - true
    app.provider.user_token:
        class: "%app.class.token_user_provider%"
        arguments:
            - "@doctrine.orm.default_entity_manager"
