parent_box: debian/jessie64
#parent_box: ubuntu/trusty64
box: sf-demo
name: my-sf-demo
memory: 512
cpus: 1
ip: 192.168.1.128
shell_inline: |
    dpkg -l docker-engine 1>/dev/null 2>&1 || {
        {
            echo export LC_ALL=${locale}
            echo export LANG=${locale}
            echo export LANGUAGE=${locale}
        } >> /etc/profile \
        && {
            echo LANGUAGE=${locale}
            echo LC_ALL=${locale}
            echo LANG=${locale}
            echo LC_TYPE=${locale}
        } > /etc/default/locale \
        && apt-get -o Dpkg::Options::="--force-confold" install --reinstall locales \
        && apt-key adv --keyserver ${apt_key_dsn} --recv-keys ${apt_key_recv} \
        && echo ${apt_source_string} > ${apt_docker_source_path} \
        && apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
        && apt-get update \
        && apt-get upgrade -y \
        && apt-get install -y --force-yes docker-engine="${docker_engine_version}" \
        && apt-mark hold docker-engine \
        && usermod -aG docker vagrant \
        && curl -L ${docker_compose_url} > ${docker_compose_path} \
        && chmod +x ${docker_compose_path}
    }
