box: debian/jessie64
name: sf-demo-pack
runtime_name: sf-demo
memory: 512
cpus: 1
ip: 192.168.50.12
shell_provision: |
  dpkg -l docker-engine 1>/dev/null 2>&1 || {
  locale=en_US.UTF-8
  dc_path=/usr/local/bin/docker-compose
  {
    echo export LC_ALL=${locale}
    echo export LANG=${locale}
    echo export LANGUAGE=${locale}
  } >> /etc/profile \
  && {
    echo LANGUAGE=${locale}
    echo LC_ALL=${locale}
    echo LANG=${locale}
    echo LC_TYPE=${locale}
  } > /etc/default/locale \
  && locale-gen ${locale} \
  && apt-get -o Dpkg::Options::="--force-confold" install --reinstall locales \
  && apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D \
  && echo deb https://apt.dockerproject.org/repo debian-jessie main > /etc/apt/sources.list.d/docker.list \
  && apt-get install -y \
      apt-transport-https \
      ca-certificates \
      curl \
  && apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y --force-yes docker-engine="1.12.2-0~jessie" \
  && apt-mark hold docker-engine \
  && usermod -aG docker vagrant \
  && curl -L https://github.com/docker/compose/releases/download/1.9.0/run.sh > ${dc_path} \
  && chmod +x ${dc_path}
  }
