version: "2"
services:
    back:
        build: ./php-fpm
        depends_on: ["db"]
        environment:
            TERM: rxvt
        hostname: back
        ports:
            - "9000:9000"
        volumes:
#            - ./volume/var/run:/var/run
            - ./../symfony:/usr/share/sf-security-demo
    db:
        build: ./mysql
        environment:
            TERM: rxvt
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
        hostname: db
        ports:
            - "3306:3306"
    front:
        build: ./nginx
        depends_on: ["back"]
        environment:
            TERM: rxvt
        hostname: front
        ports:
            - "80:80"
        volumes_from:
            - back
